// AUTO-GENERATED by scripts/extract-quiz.mjs, curated by scripts/apply-quiz-scope-cleanup.mjs — do not hand-edit.
export interface QuizSetMeta {
  setNumber: number;
  questionCount: number;
}

export const quizSetsMeta: QuizSetMeta[] = [
  {
    "setNumber": 1,
    "questionCount": 44
  },
  {
    "setNumber": 2,
    "questionCount": 43
  },
  {
    "setNumber": 3,
    "questionCount": 36
  },
  {
    "setNumber": 4,
    "questionCount": 39
  },
  {
    "setNumber": 5,
    "questionCount": 36
  },
  {
    "setNumber": 9,
    "questionCount": 54
  },
  {
    "setNumber": 10,
    "questionCount": 51
  },
  {
    "setNumber": 11,
    "questionCount": 55
  },
  {
    "setNumber": 12,
    "questionCount": 56
  },
  {
    "setNumber": 13,
    "questionCount": 53
  },
  {
    "setNumber": 14,
    "questionCount": 57
  },
  {
    "setNumber": 15,
    "questionCount": 56
  },
  {
    "setNumber": 16,
    "questionCount": 57
  },
  {
    "setNumber": 17,
    "questionCount": 29
  },
  {
    "setNumber": 18,
    "questionCount": 39
  },
  {
    "setNumber": 19,
    "questionCount": 38
  },
  {
    "setNumber": 20,
    "questionCount": 40
  },
  {
    "setNumber": 21,
    "questionCount": 34
  },
  {
    "setNumber": 22,
    "questionCount": 34
  },
  {
    "setNumber": 23,
    "questionCount": 40
  },
  {
    "setNumber": 24,
    "questionCount": 16
  }
];
