// AUTO-GENERATED by scripts/extract-quiz.mjs — do not hand-edit; re-run the script instead.
export interface QuizSetMeta {
  setNumber: number;
  questionCount: number;
}

export const quizSetsMeta: QuizSetMeta[] = [
  {
    "setNumber": 1,
    "questionCount": 54
  },
  {
    "setNumber": 2,
    "questionCount": 54
  },
  {
    "setNumber": 3,
    "questionCount": 48
  },
  {
    "setNumber": 4,
    "questionCount": 52
  },
  {
    "setNumber": 5,
    "questionCount": 56
  },
  {
    "setNumber": 6,
    "questionCount": 43
  },
  {
    "setNumber": 7,
    "questionCount": 53
  },
  {
    "setNumber": 8,
    "questionCount": 9
  },
  {
    "setNumber": 9,
    "questionCount": 57
  },
  {
    "setNumber": 10,
    "questionCount": 59
  },
  {
    "setNumber": 11,
    "questionCount": 60
  },
  {
    "setNumber": 12,
    "questionCount": 59
  },
  {
    "setNumber": 13,
    "questionCount": 57
  },
  {
    "setNumber": 14,
    "questionCount": 59
  },
  {
    "setNumber": 15,
    "questionCount": 59
  },
  {
    "setNumber": 16,
    "questionCount": 60
  },
  {
    "setNumber": 17,
    "questionCount": 30
  },
  {
    "setNumber": 18,
    "questionCount": 54
  },
  {
    "setNumber": 19,
    "questionCount": 57
  },
  {
    "setNumber": 20,
    "questionCount": 54
  },
  {
    "setNumber": 21,
    "questionCount": 55
  },
  {
    "setNumber": 22,
    "questionCount": 54
  },
  {
    "setNumber": 23,
    "questionCount": 50
  },
  {
    "setNumber": 24,
    "questionCount": 25
  }
];
