// One-off extraction script: parses others/quiz/Practice_Set_*.html (SkillCertPro
// practice quizzes) into a single structured JSON file, without altering any prose.
// Run with: node scripts/extract-quiz.mjs
import fs from 'node:fs';
import path from 'node:path';
import * as cheerio from 'cheerio';

const root = new URL('..', import.meta.url).pathname;
const quizDir = path.join(root, 'others/quiz');
const outDataDir = path.join(root, 'src/quiz/data');
const outMetaFile = path.join(root, 'src/quiz/meta.ts');

fs.mkdirSync(outDataDir, { recursive: true });

const files = fs
  .readdirSync(quizDir)
  .filter((f) => /^Practice_Set_\d+\.html$/.test(f))
  .sort((a, b) => {
    const na = Number(a.match(/\d+/)[0]);
    const nb = Number(b.match(/\d+/)[0]);
    return na - nb;
  });

console.log(`Found ${files.length} quiz files`);

function cleanText(s) {
  return s.replace(/\s+/g, ' ').trim();
}

const sets = files.map((file) => {
  const setNumber = Number(file.match(/\d+/)[0]);
  const html = fs.readFileSync(path.join(quizDir, file), 'utf8');
  const $ = cheerio.load(html);

  const items = $('body > div > ol > li').toArray();
  const questions = items.map((el, idx) => {
    const $li = $(el);
    const divs = $li.children('div');
    if (divs.length < 2) {
      throw new Error(`${file} question ${idx + 1}: expected 2 top-level divs, found ${divs.length}`);
    }
    const qDiv = divs.eq(0);
    const explDiv = divs.eq(1);

    const optionsUl = qDiv.children('ul').first();
    if (optionsUl.length === 0) {
      throw new Error(`${file} question ${idx + 1}: no options <ul> found`);
    }

    // Question text: everything in qDiv before the options <ul> (usually one <p>,
    // occasionally more than one paragraph).
    const questionParas = qDiv
      .children()
      .not(optionsUl)
      .map((_, p) => cleanText($(p).text()))
      .get()
      .filter(Boolean);
    const questionText = questionParas.join('\n\n');

    const options = optionsUl
      .children('li')
      .map((_, optEl) => {
        const $opt = $(optEl);
        const correct = $opt.find('strong').filter((_, s) => /\(correct\)/i.test($(s).text())).length > 0;
        const $clone = $opt.clone();
        $clone.find('strong').filter((_, s) => /\(correct\)/i.test($(s).text())).remove();
        const text = cleanText($clone.text());
        return { text, correct };
      })
      .get();

    if (!options.some((o) => o.correct)) {
      throw new Error(`${file} question ${idx + 1}: no correct option marked`);
    }

    // Explanation: full inner HTML of the second div, minus a leading
    // "<p><strong>Explanation</strong></p>" boilerplate header if present.
    const $expl = explDiv.clone();
    const firstP = $expl.children('p').first();
    if (firstP.length && /^explanation$/i.test(cleanText(firstP.text()))) {
      firstP.remove();
    }
    // Strip inline event handlers (e.g. onclick="javascript:window.open(...)")
    // and force external links to open safely in a new tab.
    $expl.find('*').each((_, node) => {
      const attribs = node.attribs || {};
      for (const name of Object.keys(attribs)) {
        if (/^on/i.test(name)) $(node).removeAttr(name);
      }
    });
    $expl.find('a[href]').attr('target', '_blank').attr('rel', 'noopener');
    const explanationHtml = $expl.html().trim();

    const numberLabel = cleanText($li.find('> h3').first().text());
    const number = Number((numberLabel.match(/\d+/) || [idx + 1])[0]);

    return {
      id: `${setNumber}-${number}`,
      number,
      text: questionText,
      options,
      multiSelect: options.filter((o) => o.correct).length > 1,
      explanationHtml,
    };
  });

  return { setNumber, sourceFile: file, questionCount: questions.length, questions };
});

for (const set of sets) {
  const outFile = path.join(outDataDir, `set-${set.setNumber}.json`);
  fs.writeFileSync(outFile, JSON.stringify(set, null, 2) + '\n');
}

const metaEntries = sets.map((s) => ({ setNumber: s.setNumber, questionCount: s.questionCount }));
const metaContent = `// AUTO-GENERATED by scripts/extract-quiz.mjs — do not hand-edit; re-run the script instead.
export interface QuizSetMeta {
  setNumber: number;
  questionCount: number;
}

export const quizSetsMeta: QuizSetMeta[] = ${JSON.stringify(metaEntries, null, 2)};
`;
fs.writeFileSync(outMetaFile, metaContent);

const totalQuestions = sets.reduce((sum, s) => sum + s.questionCount, 0);
console.log(`Wrote ${sets.length} files to ${outDataDir}`);
console.log(`Wrote ${outMetaFile}`);
console.log(`${sets.length} sets, ${totalQuestions} questions total`);
