// AUTO-GENERATED by scripts/extract-content.mjs — do not hand-edit; re-run the script instead.
export interface DomainBullet { text: string; glossId: string; }
export interface DomainSubsection { id: string; title: string; bullets: DomainBullet[]; }
export interface DomainData { number: number; kicker: string; name: string; nameOrig: string; weight: string; subsections: DomainSubsection[]; }

export const domains: DomainData[] = [
  {
    "number": 1,
    "kicker": "Dominio 1",
    "name": "Fundamentos de IA y ML",
    "nameOrig": "Fundamentals of AI and ML",
    "weight": "20%",
    "subsections": [
      {
        "id": "1.1",
        "title": "Explicar conceptos y terminología básica de IA",
        "bullets": [
          {
            "text": "Definir términos básicos de IA (IA, ML, deep learning, redes neuronales, visión por computadora, NLP, modelo, algoritmo, entrenamiento e inferencia, sesgo, equidad, ajuste/fit, LLM, GenAI, IA agéntica).",
            "glossId": "gloss-d1-t1-b1"
          },
          {
            "text": "Describir las similitudes y diferencias entre IA, ML, GenAI, deep learning e IA agéntica.",
            "glossId": "gloss-d1-t1-b2"
          },
          {
            "text": "Describir los distintos tipos de inferencia (por lotes, en tiempo real, asíncrona, serverless).",
            "glossId": "gloss-d1-t1-b3"
          },
          {
            "text": "Describir los distintos tipos de datos en modelos de IA (etiquetados/sin etiquetar, tabulares, series de tiempo, imagen, texto, estructurados/no estructurados).",
            "glossId": "gloss-d1-t1-b4"
          },
          {
            "text": "Describir los distintos tipos de aprendizaje de IA/ML (supervisado, no supervisado, aprendizaje por refuerzo).",
            "glossId": "gloss-d1-t1-b5"
          }
        ]
      },
      {
        "id": "1.2",
        "title": "Identificar casos de uso prácticos para IA",
        "bullets": [
          {
            "text": "Reconocer aplicaciones donde IA/ML aportan valor (apoyar la toma de decisiones humanas, escalabilidad de soluciones, automatización).",
            "glossId": "gloss-d1-t2-b1"
          },
          {
            "text": "Determinar cuándo una solución de IA/ML no es apropiada (análisis costo-beneficio, situaciones que requieren un resultado específico en vez de una predicción).",
            "glossId": "gloss-d1-t2-b2"
          },
          {
            "text": "Seleccionar las técnicas de IA/ML apropiadas para casos de uso específicos (regresión, clasificación, clustering).",
            "glossId": "gloss-d1-t2-b3"
          },
          {
            "text": "Identificar ejemplos de aplicaciones reales de IA (visión por computadora, NLP, reconocimiento de voz, sistemas de recomendación, detección de fraude, pronósticos, bases de conocimiento, IA agéntica).",
            "glossId": "gloss-d1-t2-b4"
          },
          {
            "text": "Explicar las capacidades de los servicios administrados de IA/ML de AWS (Amazon SageMaker AI, Amazon Transcribe, Amazon Translate, Amazon Comprehend, Amazon Lex, Amazon Polly).",
            "glossId": "gloss-d1-t2-b5"
          },
          {
            "text": "Identificar cuándo conviene usar modelos de ML tradicionales o foundation models (FMs) (por regulación, requisitos de explicabilidad, restricciones operativas).",
            "glossId": "gloss-d1-t2-b6"
          }
        ]
      },
      {
        "id": "1.3",
        "title": "Describir el ciclo de vida de desarrollo de IA/ML",
        "bullets": [
          {
            "text": "Describir y diferenciar los componentes de un pipeline de IA/ML.",
            "glossId": "gloss-d1-t3-b1"
          },
          {
            "text": "Describir las fuentes de los FMs (modelos preentrenados de código abierto, entrenamiento de modelos propios).",
            "glossId": "gloss-d1-t3-b2"
          },
          {
            "text": "Describir métodos para poner un modelo en producción (servicio de API administrado, API auto-alojada).",
            "glossId": "gloss-d1-t3-b3"
          },
          {
            "text": "Identificar los servicios y funciones de AWS relevantes en cada etapa del pipeline de IA/ML (Amazon Bedrock, Amazon Quick, Kiro, SageMaker AI).",
            "glossId": "gloss-d1-t3-b4"
          },
          {
            "text": "Describir los conceptos fundamentales de MLOps (experimentación, procesos repetibles, sistemas escalables, gestión de deuda técnica, preparación para producción, monitoreo del modelo, reentrenamiento).",
            "glossId": "gloss-d1-t3-b5"
          },
          {
            "text": "Describir métricas de desempeño del modelo (accuracy, precisión, recall, F1) y métricas de negocio (costo por usuario, costos de desarrollo, feedback de clientes, ROI) para evaluar modelos de ML.",
            "glossId": "gloss-d1-t3-b6"
          }
        ]
      }
    ]
  },
  {
    "number": 2,
    "kicker": "Dominio 2",
    "name": "Fundamentos de la IA generativa",
    "nameOrig": "Fundamentals of GenAI",
    "weight": "24%",
    "subsections": [
      {
        "id": "2.1",
        "title": "Explicar los conceptos básicos de la IA generativa",
        "bullets": [
          {
            "text": "Definir conceptos fundamentales de GenAI (tokens, chunking, embeddings, vectores, prompt engineering, LLMs basados en transformers, FMs, modelos multimodales, modelos de difusión).",
            "glossId": "gloss-d2-t1-b1"
          },
          {
            "text": "Identificar posibles casos de uso para modelos de GenAI (generación de imagen/video/audio, resumen, asistentes de IA, traducción, generación de código, agentes de servicio al cliente, búsqueda, motores de recomendación).",
            "glossId": "gloss-d2-t1-b2"
          },
          {
            "text": "Describir el ciclo de vida de un FM (selección de datos, selección del modelo, preentrenamiento, fine-tuning, evaluación, despliegue, retroalimentación).",
            "glossId": "gloss-d2-t1-b3"
          },
          {
            "text": "Describir el modelo de precios basado en tokens y su efecto en el costo y desempeño de la inferencia.",
            "glossId": "gloss-d2-t1-b4"
          },
          {
            "text": "Describir el rol de la ingeniería de contexto en aplicaciones basadas en FMs.",
            "glossId": "gloss-d2-t1-b5"
          },
          {
            "text": "Definir conceptos fundamentales de IA agéntica (patrones de sistemas multiagente, Model Context Protocol [MCP] y su rol conectando agentes con sistemas externos, patrones de comunicación entre agentes, gestión de memoria, uso de herramientas, orquestación de flujos de trabajo).",
            "glossId": "gloss-d2-t1-b6"
          }
        ]
      },
      {
        "id": "2.2",
        "title": "Comprender las capacidades y limitaciones de la GenAI para resolver problemas de negocio",
        "bullets": [
          {
            "text": "Describir las ventajas de la GenAI (adaptabilidad, capacidad de respuesta, capacidades conversacionales, generación de contenido).",
            "glossId": "gloss-d2-t2-b1"
          },
          {
            "text": "Identificar las desventajas de las soluciones de GenAI (alucinaciones, interpretabilidad, imprecisión, no determinismo).",
            "glossId": "gloss-d2-t2-b2"
          },
          {
            "text": "Identificar factores a considerar al elegir modelos de GenAI (tipo de modelo, requisitos de desempeño, capacidades, restricciones, cumplimiento normativo, costo, latencia, complejidad del modelo).",
            "glossId": "gloss-d2-t2-b3"
          },
          {
            "text": "Determinar el valor de negocio y las métricas de las aplicaciones de GenAI (desempeño entre dominios, ROI, eficiencia, tasa de conversión, ingreso promedio por usuario, exactitud, valor de vida del cliente).",
            "glossId": "gloss-d2-t2-b4"
          }
        ]
      },
      {
        "id": "2.3",
        "title": "Describir la infraestructura y tecnologías de AWS para construir aplicaciones de GenAI",
        "bullets": [
          {
            "text": "Identificar los servicios y funciones de AWS para desarrollar aplicaciones de GenAI (Amazon Bedrock, SageMaker AI, SageMaker JumpStart, Amazon Quick, Kiro, Strands Agents, Amazon Bedrock AgentCore).",
            "glossId": "gloss-d2-t3-b1"
          },
          {
            "text": "Describir las ventajas de usar servicios de GenAI de AWS para construir aplicaciones (accesibilidad, menor barrera de entrada, eficiencia, costo-efectividad, velocidad de salida al mercado).",
            "glossId": "gloss-d2-t3-b2"
          },
          {
            "text": "Describir los beneficios de la infraestructura de AWS para aplicaciones de GenAI (seguridad, cumplimiento normativo, responsabilidad, safety).",
            "glossId": "gloss-d2-t3-b3"
          },
          {
            "text": "Describir las contrapartidas de costo de los servicios de GenAI de AWS (capacidad de respuesta, disponibilidad, redundancia, desempeño, cobertura regional, precios por token, throughput aprovisionado, modelos personalizados).",
            "glossId": "gloss-d2-t3-b4"
          }
        ]
      }
    ]
  },
  {
    "number": 3,
    "kicker": "Dominio 3 · el que más pesa",
    "name": "Aplicaciones de foundation models",
    "nameOrig": "Applications of Foundation Models",
    "weight": "28%",
    "subsections": [
      {
        "id": "3.1",
        "title": "Describir consideraciones de diseño para aplicaciones que usan FMs",
        "bullets": [
          {
            "text": "Identificar los criterios de selección para elegir FMs (costo, modalidad, latencia, soporte multilingüe, tamaño del modelo, complejidad, personalización, longitud de entrada/salida, prompt caching).",
            "glossId": "gloss-d3-t1-b1"
          },
          {
            "text": "Describir el efecto de los parámetros de inferencia en las respuestas del modelo (temperatura, longitud de entrada/salida).",
            "glossId": "gloss-d3-t1-b2"
          },
          {
            "text": "Definir Retrieval Augmented Generation (RAG) y describir sus aplicaciones de negocio (Amazon Bedrock Knowledge Bases).",
            "glossId": "gloss-d3-t1-b3"
          },
          {
            "text": "Identificar los servicios de AWS que ayudan a almacenar embeddings en bases de datos vectoriales (Amazon OpenSearch Service, Amazon Aurora, Amazon Neptune, Amazon RDS para PostgreSQL).",
            "glossId": "gloss-d3-t1-b4"
          },
          {
            "text": "Explicar las contrapartidas de costo de los distintos enfoques de personalización de FMs (preentrenamiento, fine-tuning, in-context learning, RAG, destilación de modelos).",
            "glossId": "gloss-d3-t1-b5"
          },
          {
            "text": "Definir el rol de los agentes de IA y describir sus aplicaciones de negocio.",
            "glossId": "gloss-d3-t1-b6"
          }
        ]
      },
      {
        "id": "3.2",
        "title": "Elegir técnicas efectivas de ingeniería de prompts",
        "bullets": [
          {
            "text": "Definir los conceptos y elementos de la ingeniería de prompts (contexto, instrucción, prompts negativos).",
            "glossId": "gloss-d3-t2-b1"
          },
          {
            "text": "Definir técnicas de ingeniería de prompts (chain-of-thought, zero-shot, single-shot, few-shot, plantillas de prompts).",
            "glossId": "gloss-d3-t2-b2"
          },
          {
            "text": "Identificar y describir los beneficios y buenas prácticas de la ingeniería de prompts (mejora de la calidad de respuesta, experimentación, guardrails, descubrimiento, especificidad y concisión, uso de múltiples comentarios).",
            "glossId": "gloss-d3-t2-b3"
          },
          {
            "text": "Definir los riesgos y limitaciones potenciales de la ingeniería de prompts (exposición, envenenamiento/poisoning, secuestro/hijacking, jailbreaking).",
            "glossId": "gloss-d3-t2-b4"
          },
          {
            "text": "Describir estrategias de versionado y gestión de prompts usando Amazon Bedrock Prompt Management.",
            "glossId": "gloss-d3-t2-b5"
          }
        ]
      },
      {
        "id": "3.3",
        "title": "Describir el proceso de entrenamiento y fine-tuning de FMs",
        "bullets": [
          {
            "text": "Describir los elementos clave del entrenamiento de un FM (preentrenamiento, fine-tuning, preentrenamiento continuo, destilación).",
            "glossId": "gloss-d3-t3-b1"
          },
          {
            "text": "Definir métodos de fine-tuning de un FM (instruction tuning, adaptación de modelos a dominios específicos, transfer learning, preentrenamiento continuo).",
            "glossId": "gloss-d3-t3-b2"
          },
          {
            "text": "Describir cómo preparar los datos para hacer fine-tuning a un FM (curaduría de datos, gobernanza, tamaño, etiquetado, representatividad, aprendizaje por refuerzo con retroalimentación humana [RLHF]).",
            "glossId": "gloss-d3-t3-b3"
          }
        ]
      },
      {
        "id": "3.4",
        "title": "Describir métodos para evaluar el desempeño de los FMs",
        "bullets": [
          {
            "text": "Determinar enfoques para evaluar el desempeño de un FM (evaluación human-in-the-loop, datasets de referencia/benchmark, Amazon Bedrock Model Evaluation).",
            "glossId": "gloss-d3-t4-b1"
          },
          {
            "text": "Identificar las métricas relevantes para evaluar el desempeño de un FM (ROUGE, BLEU, BERTScore, LLM-as-a-judge).",
            "glossId": "gloss-d3-t4-b2"
          },
          {
            "text": "Determinar si un FM cumple efectivamente con los objetivos de negocio (productividad, engagement de usuarios, task engineering).",
            "glossId": "gloss-d3-t4-b3"
          },
          {
            "text": "Identificar enfoques para evaluar el desempeño de aplicaciones construidas con FMs (RAG, agentes, flujos de trabajo).",
            "glossId": "gloss-d3-t4-b4"
          },
          {
            "text": "Identificar métricas de alineación con objetivos de negocio para aplicaciones de IA (tasa de finalización de tareas, satisfacción del usuario, costo por interacción).",
            "glossId": "gloss-d3-t4-b5"
          }
        ]
      }
    ]
  },
  {
    "number": 4,
    "kicker": "Dominio 4",
    "name": "Lineamientos para una IA responsable",
    "nameOrig": "Guidelines for Responsible AI",
    "weight": "14%",
    "subsections": [
      {
        "id": "4.1",
        "title": "Explicar el desarrollo de sistemas de IA responsables",
        "bullets": [
          {
            "text": "Identificar las características de una IA responsable (sesgo, equidad, inclusividad, robustez, seguridad, veracidad).",
            "glossId": "gloss-d4-t1-b1"
          },
          {
            "text": "Explicar cómo usar herramientas para identificar características de IA responsable (Amazon Bedrock Guardrails).",
            "glossId": "gloss-d4-t1-b2"
          },
          {
            "text": "Definir prácticas responsables para seleccionar un modelo (consideraciones ambientales, sostenibilidad).",
            "glossId": "gloss-d4-t1-b3"
          },
          {
            "text": "Identificar los riesgos legales de trabajar con GenAI (reclamos por infracción de propiedad intelectual, resultados sesgados del modelo, pérdida de confianza del cliente, riesgo para el usuario final, alucinaciones).",
            "glossId": "gloss-d4-t1-b4"
          },
          {
            "text": "Identificar las características de los conjuntos de datos (inclusividad, diversidad, fuentes de datos curadas, datasets balanceados).",
            "glossId": "gloss-d4-t1-b5"
          },
          {
            "text": "Describir los efectos del sesgo y la varianza (efectos sobre grupos demográficos, imprecisión, overfitting, underfitting).",
            "glossId": "gloss-d4-t1-b6"
          },
          {
            "text": "Describir herramientas para detectar y monitorear el sesgo, la confiabilidad y la veracidad (análisis de calidad de etiquetas, auditorías humanas, análisis de subgrupos).",
            "glossId": "gloss-d4-t1-b7"
          }
        ]
      },
      {
        "id": "4.2",
        "title": "Reconocer la importancia de los modelos transparentes y explicables",
        "bullets": [
          {
            "text": "Describir las diferencias entre modelos transparentes/explicables y modelos que no lo son.",
            "glossId": "gloss-d4-t2-b1"
          },
          {
            "text": "Describir herramientas para identificar modelos transparentes y explicables (Amazon SageMaker Model Cards, Amazon Bedrock Model Evaluations, modelos, datos y licenciamiento de código abierto).",
            "glossId": "gloss-d4-t2-b2"
          },
          {
            "text": "Identificar las contrapartidas entre la seguridad del modelo y su transparencia (interpretabilidad frente a desempeño).",
            "glossId": "gloss-d4-t2-b3"
          },
          {
            "text": "Describir los principios del diseño centrado en el humano para una IA explicable (mecanismos de retroalimentación del usuario, transparencia en las decisiones de la IA).",
            "glossId": "gloss-d4-t2-b4"
          }
        ]
      }
    ]
  },
  {
    "number": 5,
    "kicker": "Dominio 5",
    "name": "Seguridad, cumplimiento y gobernanza para soluciones de IA",
    "nameOrig": "Security, Compliance, and Governance for AI Solutions",
    "weight": "14%",
    "subsections": [
      {
        "id": "5.1",
        "title": "Explicar métodos para asegurar sistemas de IA",
        "bullets": [
          {
            "text": "Identificar los servicios y funciones de AWS para asegurar sistemas de IA (roles, políticas y permisos de IAM; cifrado; Amazon Macie; AWS PrivateLink; modelo de responsabilidad compartida de AWS; Amazon Bedrock AgentCore Identity; Policy en AgentCore; Amazon Bedrock Guardrails).",
            "glossId": "gloss-d5-t1-b1"
          },
          {
            "text": "Describir el concepto de citación de fuentes y documentación del origen de los datos (linaje de datos, catalogación de datos, Amazon SageMaker Model Cards).",
            "glossId": "gloss-d5-t1-b2"
          },
          {
            "text": "Describir las buenas prácticas de ingeniería de datos segura (evaluación de la calidad de los datos, tecnologías que mejoran la privacidad, control de acceso a los datos, integridad de los datos).",
            "glossId": "gloss-d5-t1-b3"
          },
          {
            "text": "Describir las consideraciones de seguridad y privacidad para sistemas de IA (seguridad de aplicaciones, detección de amenazas, gestión de vulnerabilidades, protección de infraestructura, inyección de prompts, cifrado en reposo y en tránsito, prevención de fuga de datos, filtrado y validación de salidas, requisitos de auditoría y registro de interacciones de IA, toxicidad).",
            "glossId": "gloss-d5-t1-b4"
          },
          {
            "text": "Describir métodos de detección de alucinaciones y técnicas de grounding para mejorar la precisión de las salidas (grounding con RAG, validación de salidas, puntuación de confianza).",
            "glossId": "gloss-d5-t1-b5"
          }
        ]
      },
      {
        "id": "5.2",
        "title": "Reconocer regulaciones de gobernanza y cumplimiento para sistemas de IA",
        "bullets": [
          {
            "text": "Identificar los servicios y funciones de AWS que ayudan con la gobernanza y el cumplimiento normativo (AWS Config, Amazon Inspector, AWS Artifact, AWS CloudTrail, AWS Trusted Advisor).",
            "glossId": "gloss-d5-t2-b1"
          },
          {
            "text": "Describir estrategias de gobernanza de datos (ciclos de vida de los datos, registro/logging, residencia de datos, monitoreo, observación, retención).",
            "glossId": "gloss-d5-t2-b2"
          },
          {
            "text": "Describir los procesos para seguir protocolos de gobernanza (políticas, periodicidad y estrategias de revisión, marcos de gobernanza como el Generative AI Security Scoping Matrix, estándares de transparencia, requisitos de capacitación del equipo).",
            "glossId": "gloss-d5-t2-b3"
          }
        ]
      }
    ]
  }
];

export const domainByNumber: Record<number, DomainData> = Object.fromEntries(domains.map((d) => [d.number, d]));
